language: objective-c
osx_image: xcode8.2

before_install:
  - gem update
  - gem install xcpretty -N || true
  - brew update; brew update; brew upgrade
  - brew install swiftlint || true
  - brew install xctool || true
  - pod repo update
  - set -o pipefail
script: 
  - xcodebuild -workspace nWorkout.xcworkspace -scheme nWorkout -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build test | xcpretty -c
    ##- xcodebuild -workspace nWorkout.xcworkspace -scheme nWorkout -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.2' | xcpretty -c
    ##- xctool -workspace nWorkout.xcworkspace -scheme nWorkout -sdk iphonesimulator -arch 1386 run-tests


