language: objective-c
osx_image: xcode8.2
xcode_workspace: nWorkout.xcworkspace
xcode_scheme: nWorkout
xcode_sdk: iphonesimulator10.2

before_install:
  - brew udpate
  - brew outdated xctool || brew upgrade xctool
  - brew outdated xcpretty || brew upgrade xcpretty

  
script: 
  xctool -workspace nWorkout.xcworkspace -scheme nWorkout -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
  xctool test -workspace nWorkout.xcworkspace -scheme nWorkout -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty


